# Generated by Django 6.0.4 on 2026-04-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('personas', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('zona', models.CharField(choices=[('barra', 'Barra'), ('mesa', 'Mesa')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('confirmada', 'Confirmada'), ('llegado', 'Ha llegado'), ('no_show', 'No-show'), ('cancelada', 'Cancelada')], default='pendiente_pago', max_length=20)),
                ('importe_anticipo', models.PositiveIntegerField(default=0)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255)),
                ('notas', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fecha', 'hora', 'zona'],
            },
        ),
    ]
