# Generated by Django 5.2.7 on 2026-05-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_expira_en_zona_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='personas_barra',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserva',
            name='personas_mesa',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='zona',
            field=models.CharField(choices=[('barra', 'Barra'), ('mesa', 'Mesa'), ('combinada', 'Barra + mesas'), ('completo', 'Restaurante completo')], max_length=20),
        ),
    ]
