# Generated by Django 5.2.7 on 2026-05-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_personas_barra_reserva_personas_mesa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
