# Generated by Django 5.2.7 on 2026-06-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_reserva_servicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['fecha', 'servicio', 'hora', 'zona']},
        ),
    ]
